### ISSUE TITLE
material parameters

### ISSUE THREAD

**Issue by ErisZhang** [evouga/libshell#2]
Hi,

Thank you so much for sharing this nice implementation!

I wonder to reproduce some of the results in Chen et al "Physical simulation of environmentally induced thin shell deformation" e.g. Fig 3 and Fig 5, what would be reasonable material parameters to use including young's modulus, poisson's ratio, thickness, density etc. ?

Also in example/main.cpp line 90, is the unit _**mm**_ or _**m**_ ?

**Comment by evouga** [comment]
Hi Eris,

Units throughout the code are in kg-m-s (and Young's modulus is in Pa).

Please email my student Hsiao-Yu Chen (hsiaoyu@ices.utexas.edu) and she can give you the exact material parameters to reproduce those figures (she is away on an internship this semester, so if you don't hear back from her in reasonable time, feel free to follow up with me). But in general, for Young's modulus and Poisson's ratio we Googled reasonable values for common materials; the most important parameter by far is the thickness (Young's modulus only plays a role when the internal forces compete with external forces like gravity, since bending and stretching both scale linearly with it).

**Comment by ErisZhang** [comment]
Thank you so much Etienne!
